name: Build
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Echo test
        run: |
          echo "hi! this works!"
          dir
